### ISSUE TITLE
Selecting numeric variables under a covariate model

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/resources#22]
I loaded the "Five sources data" example
In Enter covariates I added a new column (named "sequence") with entries "1,23,4,5". 
In "Model options" under "Select numeric variables" I selected the created column "sequence. This caused the app to crash.

**Comment by arunge** [comment]
I tried to reproduce your example but I could not. With the "Five sources data" example on both versions of the app (main and beta):

1. when adding the new column 
![image](https://user-images.githubusercontent.com/16759098/171024610-7a3d6836-67ca-4b7a-adf4-11df951d90e2.png)

- with **default model options** but following numeric variable:
![image](https://user-images.githubusercontent.com/16759098/171024855-cf7642d8-1cf4-4a64-84f8-8af159e1fb2d.png)

I could run the model without errors:

![image](https://user-images.githubusercontent.com/16759098/171025937-988746c5-b614-4cbc-b019-06bd23d29094.png)


2. When adding following column:

![image](https://user-images.githubusercontent.com/16759098/171025172-ce4a5fc5-95bd-40f5-a639-def25fddd02f.png)

It was not possible to select a numeric column, because there was no numeric column found (because of the missing value)

![image](https://user-images.githubusercontent.com/16759098/171025337-69c4c790-971b-4467-a69d-216b32fb3cb1.png)

@isomemo Have you changed any other model options here?

**Comment by isomemo** [comment]
I also cannot reproduce this now!
