### ISSUE TITLE
Wrong display of results

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/resources#29]
[2022-06-06_12_37_24_fruitsModel.zip](https://github.com/Pandora-IsoMemo/resources/files/8843776/2022-06-06_12_37_24_fruitsModel.zip)
![Bug protein](https://user-images.githubusercontent.com/101706974/172145506-01457d4a-0971-4428-ae6f-65cfe0dbd703.PNG)

For the attached model, I have 4 user estimates groups. When I select group "protein" in Output -> Select group of estimates -> User Estimates Protein, a graph is shown with the first seven boxplots correspond to the individual estimates within the group "protein". However, a boxplot is added at the end that does not belong to the group. This boxplot is from a different group "Macros" (See attached figure).

@arunge

**Comment by CarloCocozza** [comment]
The same problem takes place for the summary results.  as you can see in the attached file, the Protein contribution estimates also include estimates from the group macros.

[isotopeData (2).xlsx](https://github.com/Pandora-IsoMemo/resources/files/8843832/isotopeData.2.xlsx)
@arunge

**Comment by CarloCocozza** [comment]
I think that the previous might be related with naming since the macros estimate which is being erroneously included is named "Macros.ProteinMAcros". Grouping should be based on indices not naming.
@arunge

**Comment by mgross** [comment]
This is fixed in the next version

**Comment by arunge** [comment]
Thanks @mgross for supporting here. This is fixed with version 22.6.2, currently available on the beta: https://isomemoapp.com/app/resources-beta; soon also on the main.

![image](https://user-images.githubusercontent.com/16759098/173586431-2976a5d0-b72e-412b-943e-f83e8b1dd47a.png)

@CarloCocozza I am closing here. If there is anything left, just reopen again or open a new issue.
