### ISSUE TITLE
Bug when deleting targets

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/resources#32]
For the attached model, when I delete the target named "cluster 1", I get the error shown in the attached image. 
[Tertiveri Model.zip](https://github.com/Pandora-IsoMemo/resources/files/8844377/Tertiveri.Model.zip)
![Bug concentrations](https://user-images.githubusercontent.com/101706974/172158992-f8208cb4-4a31-4ca1-a697-f9ef466069a6.PNG)

@arunge

**Comment by mgross** [comment]
The second error is technically correct, you cannot estimate a hierarchical model with only one individual (as hierarchical means that individuals have sth in common)

**Comment by jroachell15** [comment]
@mgross so is this a graphical / diaplay issue or an input-model issue?

**Comment by jroachell15** [comment]
@CarloCocozza does that make sense what Marcus said? have you given it a try with "non-hierarchical models"?

**Comment by CarloCocozza** [comment]
![Immagine 2022-07-12 142128](https://user-images.githubusercontent.com/101706974/178488419-29e73966-ab65-4b34-a733-e5ac59ed5c8a.png)

I get this error. I have also removed all priors and user estimates, but I still get this.

**Comment by jroachell15** [comment]
@mgross is there documentation for these model somewhere on how to use them? even myself, i dont know how they work or utilize them. Maybe if its good to write some documentation on how to use them to avoid the error messages.

**Comment by arunge** [comment]
I checked the issue here and could reproduce it. However, there is no interface related issue here.
And @mgross explained [above](https://github.com/Pandora-IsoMemo/resources/issues/32#issuecomment-1172298506) that the model was not used correctly.

@CarloCocozza Is there any open point here? As far as I see, I can close here. Please feel free to re-open the ticket if there is something left and let me know what should be done. Thanks!
