### ISSUE TITLE
Bug when changing names of target

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/resources#34]
[2022-06-06_14_26_05_fruitsModel.zip](https://github.com/Pandora-IsoMemo/resources/files/8844472/2022-06-06_14_26_05_fruitsModel.zip)
![Bug change name](https://user-images.githubusercontent.com/101706974/172161360-9340ea32-4e26-406e-a91d-f5d4d6024671.PNG)

For the attached model I changed the name of the Target frm "cluster 1" to "cluster 2" and I got the error showed in the attached image.
@arunge

**Comment by jroachell15** [comment]
@CarloCocozza @arunge 

I do confirm that this could be a bug, when you change the name from cluster 1 -> cluster2, the model dones't run. 

@mgross is the function string sensitive so when the user change the name of the target, the model fails?

**Comment by mgross** [comment]
@jroachell15 That is an interface problem, not a model one. When changing the name to cluster2; the source values get lost somehow (all NA) although still displayed in the app.

**Comment by mgross** [comment]
I.e. values$source in the server01.R is all NA:

Browse[1]> values$source
$default
$default$Cluster2
$default$Cluster2$D13C
          Protein LipidsCarbohydrates Bulk
C3             NA                  NA   NA
C4             NA                  NA   NA
Cattle         NA                  NA   NA
Ovicaprid      NA                  NA   NA
Pig            NA                  NA   NA
Poultry        NA                  NA   NA
Marine         NA                  NA   NA

....

**Comment by arunge** [comment]
@CarloCocozza This bug _might_ be **related to automatic updates** of fields that share dependent information. 

**Before** the name change we have following data using your example file:
target | sources | concentrations
---|---|---
![image](https://user-images.githubusercontent.com/16759098/175252725-e5684267-6a2b-485f-8bd9-57bb9ce2a749.png)|![image](https://user-images.githubusercontent.com/16759098/175252862-3a750546-cb5d-4ddb-9bbb-4efd8a6cf395.png)|![image](https://user-images.githubusercontent.com/16759098/175252943-4c52ea60-a5e5-491e-9745-09693c68c9ac.png)

**After** the name change we have following data:
target | sources | concentrations
---|---|---
![image](https://user-images.githubusercontent.com/16759098/175253384-a0b36d31-2288-4dfe-8195-2c716dfb8e6e.png)|![image](https://user-images.githubusercontent.com/16759098/175253519-4c3e7e70-2605-4e7f-8e92-40b31e5a59ca.png)|![image](https://user-images.githubusercontent.com/16759098/175253629-2fdb0506-df45-40a2-8baa-4a91d6a247b6.png)

That is, matrices on the active panel are updated correctly, see column "target", but on the other tabs ("sources" and "concentration") the selectInputs are updated but new empty matrices are created and the data gets lost.

But the issue seems to be **related to the chosen model options** also, e.g. in the "Model options" tab choosing
1. "Baseline model (no shared info)" -> leads to the observed issue above, but
2. "Individual targets (partially shared info)" -> name changes work correctly, see below

**After** the name change we have following data:
target | sources | concentrations
---|---|---
![image](https://user-images.githubusercontent.com/16759098/175257433-c8f70654-90f7-40ac-96f5-7e36a0b26b02.png)|![image](https://user-images.githubusercontent.com/16759098/175257588-cb75daa5-168b-4748-845f-dc2b3f126b91.png)|![image](https://user-images.githubusercontent.com/16759098/175257697-8324d01f-8396-4d45-9d34-c5ddc06ed363.png)

I am not sure which role do play here the model options. @mgross Could there be a reason why this happens if one takes the model options into account? Does it make sense to "loose" the information  for "Baseline model (no shared info)"  and to not loose it for "Individual targets (partially shared info)"?

However, there is **another not optimal issue** here which is definitely related to the interface:
It does make a difference
1. if one presses enter after the name change, or 
2. if one clicks outside the matrix. 

The second leads to an update of the selectInputs (above), the first does not update the selectInputs (see below):

![image](https://user-images.githubusercontent.com/16759098/175253791-bbaa6637-9d36-4a5f-b81d-5747c3f444e6.png)

@mgross Could you clarify the effects of the model options before we continue here?

**Comment by mgross** [comment]
@arunge that shouldn't be dependent on the model type. With "Individual targets (partially shared info)" there is only 1 source/concentration array/matrix for all individuals. For the baseline models there are source/concentration values for each individual seperately. That probably causes the issue. (All the automatic update stuff is not easy to change and not very robust, maybe wait until Andreas can take of this as he probably knows his stuff the best).

**Comment by arunge** [comment]
With [version 22.11.1](https://github.com/Pandora-IsoMemo/resources/pull/59#issue-1443993766) on the [beta branch](https://isomemoapp.com/app/resources-beta) I was able to fix the issue with "disappearing" table values.

When changing the name of an observation, the labels of select inputs where updated but the internal names of the list object that stores the values remained unchanged. That is why, the values were not found and the tables in _Sources_ and _Concentrations_ "disappeared". In the next step, those empty tables were interpreted as an update of the values, that is why, the values were removed in the internal list object. Even if one changed the names for observations back to the original ones, the data was lost in the _Concentrations_ and _Sources_ tables.

Now, after one changes observation names, list names are also updated and the values remain.

Regarding the error message [above](https://github.com/Pandora-IsoMemo/resources/issues/34#issue-1261782400), now the names are consistent and the error message did not pop up anymore when I tested.

@CarloCocozza Please, feel free to test the fix and let me know if all is working as expected. Thanks for your patience!
If all is fine from your side, I will close this issue.

**Comment by arunge** [comment]
Update: currently the checks are still running, but the new version should be available soon.

**Comment by CarloCocozza** [comment]
hi @arunge ,

I am sorry, but it's a messy period (I also moved to Jena) and I had no time to test this or other apps. I'll use again the apps soon for some projects, so I will test the fix and see if there are other bugs.

All the best,

**Comment by arunge** [comment]
@CarloCocozza I am closing here since the fix is now online for quite a while. Please feel free to open a new ticket if you find new issues. Thanks!
