### ISSUE TITLE
Bug not showing outputs in Beta version

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/resources#43]
For the attached model (but actually I also tried to load an example model), once the model is run, nothing happens when clicking on the different options of the "Output" button. However, when clicking on "Summary Statistics", these are shown, which means that the model run correctly.

This only happens for the current beta version (22.7.2) but not for the regular version (22.6.4).

[2022-07-07_13_10_22_fruitsModel.zip](https://github.com/Pandora-IsoMemo/resources/files/9063598/2022-07-07_13_10_22_fruitsModel.zip)

@arunge

**Comment by arunge** [comment]
@CarloCocozza Unfortunately, I cannot reproduce the issue.

Did you upload the data with a freshly started app?

Sometimes it helps to reload the app before uploading data. Updates of internal variables sometimes do not work as expected if one uploads data after already having calculated another model.

Understanding _all_ reactive values inside the app is impossible and controlling the expected behavior is sometimes quite challenging. I am always trying to improve reactive behavior by e.g. summarizing parts of code into modules and functions, and adding tests for them. 

But since I cannot reproduce the bug, there is no way to fix anything here. 
Please refresh the app by reloading the webpage before uploading data as often as possible.
If there are other issues feel free to open another ticket.
