### ISSUE TITLE
Model not saved correctly

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/resources#53]
[2022-08-03_14_52_17_fruitsModel.zip](https://github.com/Pandora-IsoMemo/resources/files/9251542/2022-08-03_14_52_17_fruitsModel.zip)

For the attached model, "Target&Target-to-Source Offsets" and "Components" table appear blank when the model is loaded. When this was saved, mentioned tables presented values.

@arunge

**Comment by CarloCocozza** [comment]
Update: 
This also happened for this other model. I have been using the beta version.

[2022-08-03_15_22_22_fruitsModel.zip](https://github.com/Pandora-IsoMemo/resources/files/9251692/2022-08-03_15_22_22_fruitsModel.zip)

**Comment by arunge** [comment]
@CarloCocozza Sorry for the delay! I can confirm that there is currently an issue with some reactive behavior after I modularized some parts of the interface. I am working on a solution. Thank you for your patience!

**Comment by arunge** [comment]
Looking deeper into the problem, this seems not to be related to the modularization of data inputs. I checked the dependencies and the updates of matrices are working as expected. It is very unlikely here, that if updates of matrices are not working for some tables that they are working for other tables. I also checked the upload of some example data, it works.
I checked the data of the first .zip file. Exactly the tables that are not updated after the upload are missing in the raw data, "targets" (1) and "components" (2):

| 2022-08-03_14_52_17_fruitsModel.zip | 2022-08-03_15_22_22_fruitsModel.zip |
|---|---|
|![image](https://user-images.githubusercontent.com/16759098/191577687-5f803435-dffc-4e75-84c1-25889944787f.png)|![image](https://user-images.githubusercontent.com/16759098/191580251-3ec9e8be-8d67-44e2-88a7-4a43a8e57162.png)|


That is, it must have been missing already when the data was saved. This might have been related to [another bug](#44) that lead to the reset of some tables after changing column names. That bug was fixed in the meanwhile.

With [the new version 22.09.1](https://github.com/Pandora-IsoMemo/resources/pull/57#issue-1381103583) on the [beta branch](https://isomemoapp.com/app/resources-beta) I updated the warnings after the upload of files. This helps to identify empty tables within the raw data:
![image](https://user-images.githubusercontent.com/16759098/191603811-7c848322-9429-4197-a283-bd022b6bf45a.png)

@CarloCocozza Would it be possible to reconstruct the model run that was done before the .zip file above was created, save the model and upload it again? Unfortunately, I cannot test if the problem described above still exists.

If the bug is still there, than it could be that some table or column names are still not set properly. If names do not match properly, it could be that data is not found after changing some labels leaving the respective matrices empty (this was the case in #44). 

Note: This also could be related to #55.

**Comment by CarloCocozza** [comment]
@arunge thanks! 
Unfortunately I do not remember all the parameters used for this model as this was a test. If I face this bug again, I will open a new issue.

**Comment by arunge** [comment]
Thanks for your patience, than I close here.
