### ISSUE TITLE
New bug: loop when deleting a column/row

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/resources#58]
For this file: 
[Cluster modelling.zip](https://github.com/Pandora-IsoMemo/resources/files/9844461/Cluster.modelling.zip)

I tried to delete the column named c13 by pressing the x to the right of the column's name:

![image](https://user-images.githubusercontent.com/46485054/197342148-cc5d7923-fdae-4e0e-8e85-ee3c6f5c01b3.png)

This launched a non-ending loop:

![image](https://user-images.githubusercontent.com/46485054/197342037-6991aa4e-c3a4-44fd-9815-c325e0c9753b.png)

Loops are shown for all tables but this is strange as tables are supposed to be independent.

**Comment by arunge** [comment]
@isomemo I think we must discuss, how to solve the issue here.

The loop occurs because the tables **are** independent but the column and row names **cannot be** independent.

Row/column names are required to correctly match the data between the target's table and the sources/concentrations tables. The names are needed to select (via the select input) the desired table in sources/concentrations. Therefor the row/column names of list and sub-lists elements are used to label data correctly.

When deleting a row/column in the target's table, it is removed in the target's table **but not** in sources or concentrations tables.

However, for fixing #34 I added a check if names of target's table and the sources/concentrations tables are matching (if not they are updated automatically -> here tables _are dependent_). But when one deletes a row this check currently fails and leads to the endless loop.

The only chance I see to fix this is to _automatically_ delete all respective list entries in sources/concentrations if one deletes a target's row or column. Then the check for matching names will work again.

However, **this will make the tables depend on each other**. And I see no other way to solve this. Please, let us discuss how to continue here.

**Comment by isomemo** [comment]
@arunge we can discuss this today! However, the best way seemt to be to make the columns and row names independent accross tables. Leaving the user to ensure that these match. Once the user runs the model a check is made if names are matching and if not an error message is generated and the model is not run.

**Comment by arunge** [comment]
As mentioned [here](https://github.com/Pandora-IsoMemo/resources/issues/58#issuecomment-1313424254) sources and concentration tables must be dependent on the table names of the targets table. If I do not update the list names of sources and concentration tables if one changes the column / row names of the target's table, the tables will again be emptied when column names are changed. (We solved [that bug](https://github.com/Pandora-IsoMemo/resources/issues/34)).
Here you see were column- (2) /rowname (1) changes must be updated:
- for sources:

   ![image](https://user-images.githubusercontent.com/16759098/205275182-645b5091-0da9-4171-b5fe-736f812fb6b4.png)

- for concentrations:

   ![image](https://user-images.githubusercontent.com/16759098/205275826-f9ce2a78-47c2-4ebe-ba38-3fbdc8675138.png)

when we change the names in the target's table:

   ![image](https://user-images.githubusercontent.com/16759098/205275643-3552919f-2819-48d0-9620-fd224be5c70d.png)

However, deleting a column is still an open issue which I did not fix yet.

Yes, let us discuss this issue in the call.

**Comment by arunge** [comment]
I could fix the bug with deleting rows/columns with [ReSources 22.12.1](https://github.com/Pandora-IsoMemo/resources/pull/69) on the [beta version](https://isomemoapp.com/app/resources-beta). When the checks have finished, the new version will be available.

In order to fix this bug, I had to restructure the logic for updating table columns and rows. I added several new tests that helped me to understand the issue while developing a solution.
In ReSources, there are many dependencies between tables and model inputs (that is why it takes so long to load the app). I hope, there is no issue left and that I could catch all different cases, such as _baseline model / no baseline model_ or _use / not use components_.

@isomemo Please test carefully several scenarios with maybe different data and let me know if there is still an open issue. Thanks for your patience!

**Comment by isomemo** [comment]
@arunge this will take some time to test. I am also preparing instructions for Marcus to fix other model-related things.

**Comment by arunge** [comment]
@isomemo Because of several bug fixes that were still only on beta but not on the main, and in order to reduce confusion what is on which version, I decided to push the current beta version to the main app. (In case this causes problems: it is always possible to revert a commit with git.)

You already opened a [new issue](https://github.com/Pandora-IsoMemo/resources/issues/86) because there are still some issues that we must discuss. I think, I can close here.

**Comment by isomemo** [comment]
@arunge Ok!
