### ISSUE TITLE
Bug on Categorical covariate variables window

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/resources#74]
For the attached model, when covariates are included in the model, and the option "random intercept (cat. vars), random slope (num. vars)" is ticked (Model Options section), a bug appears once the user tries to select these covariate variables from the window. The bug consists of a loop of automatic selection of variables.

@arunge 

[2023-02-09_12_56_00_fruitsModel.zip](https://github.com/Pandora-IsoMemo/resources/files/10696941/2023-02-09_12_56_00_fruitsModel.zip)

**Comment by arunge** [comment]
With [version 23.02.3](https://github.com/Pandora-IsoMemo/resources/pull/77) on [Resources beta](https://isomemoapp.com/app/resources-beta) this issue seems to be fixed.

I could reproduce this error online, however locally it did not occurred. Now, it seems to be fixed also online.

@CarloCocozza Could you check, please?

**Comment by CarloCocozza** [comment]
@arunge thanks! The bug seems fixed.
