### ISSUE TITLE
Export image bug

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/resources#76]
@arunge 

Export of images does not work for any of the graphs in ReSources and ReSources Beta (in Model characteristics, Model diagnostics, and Output), Error below.

![image](https://user-images.githubusercontent.com/46485054/218730032-5c3a7097-8403-4f34-be8e-93db1daf7c7b.png)

**Comment by arunge** [comment]
It looks like the tool is missing in the container but is needed for plot export. Installation instructions can be found here: https://github.com/plotly/orca#installation

@jan-abel-inwt  Can you check if it is missing and let me know tomorrow?

**Comment by jan-abel-inwt** [comment]
I have updated the dockerfile with the missing library. But we have still the same bug, but a new Error Message:

```
(orca:153): Gtk-WARNING **: 11:56:58.158: cannot open display:
```

This is caused by the `plotly:::orca_available()` function, which is trying to use `orca --help` cmd tool to check
if orca is installed on the system. But this requires XServer to work.

Fast Fix: Change the `orca_available()` function to `Sys.which("orca")` to check if orca is installed.

BUT: Orca is no longer the recommended way to do static image export and maybe its better to switch to
`Kaleido`

see https://github.com/plotly/orca/issues/349

**Comment by jan-abel-inwt** [comment]
I added the install instruction of miniconda, reticulate, kaleido & plotly in the local Dockerfile.
If the feature is working as expected, we should move these instruction to the base-image dockerfile.

**Comment by isomemo** [comment]
@jan-abel-inwt @arunge is this working now?

**Comment by jan-abel-inwt** [comment]
No yet, but i'm working on this. There is a bug with the `save_image()`  function of the plotly package we use.
I have found a workaround, but there are still some issues with dependencies.

**Comment by isomemo** [comment]
@jan-abel-inwt Ok! Thanks for the update!

**Comment by arunge** [comment]
@isomemo Just a small update here: we are still trying to identify the problem. We have implemented a solution using a different function from the ploty package `ploty::save_image`. The image export now works again when running the app version 23.02.4.2 **locally** with R **and also with docker**. Just pull with
```
docker pull ghcr.io/pandora-isomemo/resources:beta
```
and run with
```
docker run -p 3838:3838 ghcr.io/pandora-isomemo/resources:beta
```

However, we were not able to get it working on the online machine. There is an issue with the installation of some python packages. We are looking for a solution.

But at least for now you can use the local version for plot export.

**Comment by jan-abel-inwt** [comment]
@isomemo the issue is fixed. The "export image" feature works again in the beta version.
