### ISSUE TITLE
IMPORTANT BUG

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/resources#94]
@arunge when entering numbers manually into the different tables the following happens:

1) Numbers are visible in the interface
2) However, when trying to run a model an error is given that indicates that some numbers are missing. This is quite variable
3) Another diagnostic: I had an example where I had one row with 4 entries in target values. I copied and pasted this into Excel but only the two first rows were included. This explained why ReSources was sending an error instead of running.

What has changed that caused this to stop working?

**Comment by arunge** [comment]
@isomemo I understand how frustrating this must be. However, I cannot exactly say what caused the problem. With the last changes we (@mgross and me) fixed several bugs, e.g.:
- fix if `inflatedBeta == "1"`
- fix for prior generation: constraints, uncertainties
- fixes to prevent endless loops
- fix for baseline models for only 1 proxy

Unfortunately, I have not found any example data with which I could reproduce points 2. or 3.

- Could you tell what you did before the bug occurred?
  - E.g. did you change any column names or deleted a column/row (maybe not matching data lead to the problem?) 
- Do you have any example data, where the issue with missing rows is reproducible?

I need your help here in order to identify the cause of the problem.

**Comment by isomemo** [comment]
@isomemo like I said the issue is quite variable. It happened during a zoom call when researchers from another university were trying to use ReSources. Again, the numbers would appear in the table but when running the model it was like they were not there. The same thing happened when I tried to copy paste the table from ReSources to Excel. This suggests that the link between the data display variables and the variables used for modelling is sometimes not being updated as it should.

**Comment by isomemo** [comment]
@arunge close this for now! If it happens again, I will make a video.
